server:
  port: 8083
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '123'
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  security-realm: Spring Boot JWT
  jwt:
    client-id: facturia
    client-secret: facturia89codex
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: facturiaresourceid